apiVersion: apps/v1
kind: Deployment
metadata:
  name: jpetstore
  labels:
    app: jpetstore
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jpetstore
  template:
    metadata:
      labels:
        app: jpetstore
    spec:
      containers:
        - name: jpetstore
          image: yuriykhortashko/jpetstore
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
spec:
  selector:
    app: jpetstore
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080

  type: LoadBalancer
